### ISSUE TITLE
Handle errors on swap for applications with more than one CNAME

### ISSUE THREAD

**Issue by gmpify** [emerleite/tsuru-bluegreen#21]
When calling 'swap' for an application with two or more CNAMEs, I want the rollback to add all CNAMEs back to the app in live state.

Ex.:
Before the swap:
- test-blue: 2 CNAMEs
- test-green: 0 CNAMEs

Output of swap:

>  Changing live application to test-green ...
> 
>  Adding 9 'web' units to test-green ...
> Error removing cname of test-blue. Aborting...
> 
>  Removing 9 'web' units from test-green ...

After swap:
- test-blue: 1 CNAME
- test-green: 0 CNAME

**Comment by emerleite** [comment]
This is a tsuru issue: https://github.com/tsuru/tsuru/issues/1371

**Comment by gmpify** [comment]
Closing as https://github.com/tsuru/tsuru/issues/1371 is done.
