### ISSUE TITLE
Units removal retries routine throws an error when setting 'retry_times = 0'

### ISSUE THREAD

**Issue by yagossc** [emerleite/tsuru-bluegreen#38]
## Description

When trying a swap operation, in case of a non-configured `retry_times` value (which implies `retry_times = 0`), the execution crashes showing the error:
``` bash
File "/root/.tsuru/plugins/bluegreen", line 174, in remove_units_per_process_type
    Error removing '%s' units from %s in %d tries. Please, remove it manually.""" % (process_name, app, i)
UnboundLocalError: local variable 'i' referenced before assignment
```

## Steps to reproduce

Try a swap operation with a missing `[UnitsRemoval]` `.ini` section or set `retry_times = 0`.

## System settings
**Python version:** 2.7.17

**Comment by yagossc** [comment]
This `Issue` was created for documentation purposes and to inform anyone who runs into this bug. 
A PR with the fix is available [here](https://github.com/emerleite/tsuru-bluegreen/pull/39).

**Comment by anacarolinacastro** [comment]
Yago's solution at https://github.com/emerleite/tsuru-bluegreen/pull/39 fixes this issue. 

@yagossc  thanks for your contribution.
