### ISSUE TITLE
Disable New Relic when Swap

### ISSUE THREAD

**Issue by emerleite** [emerleite/tsuru-bluegreen#8]
Figure out a way to disable New Relic when Swap blue-green containers.

**Comment by andrewsmedina** [comment]
you can set an environment variable and use it to enable/disable new relic

**Comment by emerleite** [comment]
@andrewsmedina it will restart the application twice, witch is not desired.

**Comment by emerleite** [comment]
One possible solution could be: 
**swap_newrelic=true**

At **tsuru-bluegreen.ini**

**Comment by emerleite** [comment]
#15 solves this.

**Comment by emerleite** [comment]
Closed by https://github.com/emerleite/tsuru-bluegreen/commit/91dbbe2857cb3307837ff552b0bb348ace3cc5f8
